CREATE DATABASE TIMESHEET;

GRANT ALL PRIVILEGES ON TIMESHEET.* TO TIMESHEET@localhost IDENTIFIED BY 'TIMESHEET' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON TIMESHEET.* TO TIMESHEET@"%" IDENTIFIED BY 'TIMESHEET' WITH GRANT OPTION;



DROP TABLE TIMESHEET.TIMESHEETS;
DROP TABLE TIMESHEET.EMPLOYEE;


CREATE TABLE TIMESHEET.EMPLOYEE
(
	EMP_ID INTEGER AUTO_INCREMENT, 
	USER_NAME VARCHAR(30) NOT NULL, 
	PASSWORD VARCHAR(30) NOT NULL,
	EMP_NAME VARCHAR(30) NOT NULL, 
	AUTHORITY INTEGER NOT NULL, #0 IS SUPERUSER 1 IS USER
	PRIMARY KEY(EMP_ID)
);

CREATE TABLE TIMESHEET.TIMESHEETS
(
	TIMESHEET_ID INTEGER NOT NULL AUTO_INCREMENT,
	EMP_ID INTEGER NOT NULL, 
	WEEKNO INTEGER NOT NULL,
	PROJECT_ID INTEGER NOT NULL, 
	WP VARCHAR(6) NOT NULL, 
	TOTAL DECIMAL(6,2), 
	SAT DECIMAL(6,2), 
	SUN DECIMAL(6,2), 
	MON DECIMAL(6,2), 
	TUE DECIMAL(6,2), 
	WED DECIMAL(6,2), 
	THU DECIMAL(6,2), 
	FRI DECIMAL(6,2), 
	NOTES VARCHAR(30) NOT NULL,
	PRIMARY KEY(TIMESHEET_ID),
	FOREIGN KEY(EMP_ID) REFERENCES TIMESHEET.EMPLOYEE(EMP_ID) 
);

INSERT INTO TIMESHEET.EMPLOYEE VALUES( '','super','super','Bruce',0);
INSERT INTO TIMESHEET.EMPLOYEE VALUES( '','user1','user1','Huanan',1 );
INSERT INTO TIMESHEET.EMPLOYEE VALUES( '','user2','user2','Fred',1 );
INSERT INTO TIMESHEET.EMPLOYEE VALUES( '','user3','user3','Jin',1);
INSERT INTO TIMESHEET.EMPLOYEE VALUES( '','user4','user4','Bloggs',1);

INSERT INTO TIMESHEET.TIMESHEETS VALUES( '',1,52,132,'AA123','4.0','','','','4','','','','' );
INSERT INTO TIMESHEET.TIMESHEETS VALUES( '',1,52,132,'AB112','2.0','','','','2','','','','Requested by Tracy' );
INSERT INTO TIMESHEET.TIMESHEETS VALUES( '',1,52,132,'AA221','8.0','','','8.0','','','','','' );
INSERT INTO TIMESHEET.TIMESHEETS VALUES( '',1,52,1205,'12110','0.0','','','','','','','','' );
INSERT INTO TIMESHEET.TIMESHEETS VALUES( '',1,52,13000,'13000','3.5','','','','','3.5','','','' );
INSERT INTO TIMESHEET.TIMESHEETS VALUES( '',1,52,12450,'12450','10.0','','','','2.0','3.0','3.0','2.0','' );
INSERT INTO TIMESHEET.TIMESHEETS VALUES( '',1,52,32000,'32000','9.0','','','','','5.0','','4.0','' );
INSERT INTO TIMESHEET.TIMESHEETS VALUES( '',1,52,45010,'45010','9.0','','','','','','','4.0','5.0' );